[MIK-197] Add token count to novel builder
miku-gg/miku pull request #124
Opened 2024-06-18 22:48 UTC by LautaroCesso

2024-06-19 14:04 UTC, miku448 requested changes
* Token count state should be removed.
* We need to fix the prettier issue

2024-06-19 14:04 UTC, miku448 commented on apps/novel-builder/src/modals/character/CharacterDescriptionEdit.tsx
> +              });
remove `getTokens`, it is wrong and it shouldn't even exist because you MUST NOT have a global state for the token count.

2024-06-19 14:04 UTC, miku448 commented on apps/novel-builder/src/modals/character/CharacterDescriptionEdit.tsx
> +        {tokensState.totalTokens}
this should be calculated by the render function using `useMemo`

2024-06-19 14:04 UTC, miku448 commented on apps/novel-builder/src/styles/_variables.scss
> +$token-red: #d72748;
You should use the same colors we use in the interactor `_variables` instead:
https://github.com/miku-gg/miku/blob/master/apps/interactor/src/_variables.scss#L9-L11

If if looks very bad, use your colors

2024-06-19 23:02 UTC, LautaroCesso commented
<img width="1469" alt="Screenshot 2024-06-19 at 7 59 21 PM" src="https://github.com/miku-gg/miku/assets/59095036/53d3a783-f87e-43cc-a6a2-c34ebbc371b5">
<img width="1469" alt="Screenshot 2024-06-19 at 7 59 35 PM" src="https://github.com/miku-gg/miku/assets/59095036/ffa08be5-be25-4ef6-9288-d01f9f87c466">
<img width="1469" alt="Screenshot 2024-06-19 at 8 02 20 PM" src="https://github.com/miku-gg/miku/assets/59095036/dbf39685-ca74-4a57-bdb2-7685c05c782d">

2024-06-19 23:20 UTC, miku448 requested changes

2024-06-19 23:20 UTC, miku448 commented on apps/novel-builder/src/panels/index.tsx
> +  }, 0);
this calculation is wrong
it should be the `highest amount of tokens present in one of the existing scenes`.

2024-06-19 23:20 UTC, miku448 commented on apps/novel-builder/src/components/TokenDisplayer.tsx
> +          colors:
```suggestion
         This amount is the maximum *AI memory* that the text in this {isField ? 'field' : 'novel'} will take.
         The more text there is, the less conversation the AI will remember when the novel is being played.
```

2024-06-19 23:20 UTC, miku448 commented on apps/novel-builder/src/components/TokenDisplayer.tsx
> +              If the number of tokens is good for the field.
```suggestion
              If the number of tokens is good.
```

2024-06-19 23:20 UTC, miku448 commented on apps/novel-builder/src/components/TokenDisplayer.tsx
> +          This can help you to know if the text is too long for the field.
the bottom text should be something like
```
A standard novel narration has 4096 tokens of memory.
This should fit all the text considered by the AI for a given scene.
You have `scene prompt + character prompt + second character prompt (if exists) + top 3 lorebook entries (if exist) + conversation history`.
The more memory is used, the less conversation history will be taken into consideration by the AI.
```

2024-06-19 23:26 UTC, miku448 commented
You should also add token count to:
* start prompt fields
* scene prompt fields
* outfit description fields
* lorebook entry content fields

2024-06-25 00:14 UTC, miku448 requested changes

2024-06-25 00:14 UTC, miku448 commented on apps/novel-builder/src/components/TokenDisplayer.tsx
> +          remember when the novel is being played.
```suggestion
          This amount is the <b>AI memory</b> that the text
          will consume. The more text there is, the less conversation the AI will
          remember when the novel is being played.
```

2024-06-25 00:14 UTC, miku448 commented on apps/novel-builder/src/state/selectors.ts
> +    return Math.max(...scenesTokens);
```suggestion
    return Math.max(0, ...scenesTokens);
```

2024-06-25 00:14 UTC, miku448 commented on apps/novel-builder/src/state/selectors.ts
> +      });
this instead should be the maximum tokens of one the characters, since they respond one at the time.

2024-07-02 23:10 UTC, merged